name: deployar
on:
  push:
    branches:
      - main # coincicir con las ramas
env:
  AWS_ROLE: arn:aws:iam::975502669391:role/integracion-aws-con-github

jobs:
  an-example-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws_region: us-east-1
